//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clock_Alert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clock_Alert.Contents", typeof(Contents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Clock Alert.
        /// </summary>
        internal static string aboutText {
            get {
                return ResourceManager.GetString("aboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Clock Alert.
        /// </summary>
        internal static string chkUpdateText {
            get {
                return ResourceManager.GetString("chkUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off.
        /// </summary>
        internal static string clockOff {
            get {
                return ResourceManager.GetString("clockOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on.
        /// </summary>
        internal static string clockOn {
            get {
                return ResourceManager.GetString("clockOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string closeText {
            get {
                return ResourceManager.GetString("closeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! some thing went wrong while sending the crash report\nRestart the application if it doesnt work follow these steps\n1. Go to.
        /// </summary>
        internal static string crashReportErrMsgP1 {
            get {
                return ResourceManager.GetString("crashReportErrMsgP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n2. Access the log file (eg: ClockAlert&lt;date&gt;.txt)\n3. Send the log file to moon01man@gmail.com or post the contens on our FB page.
        /// </summary>
        internal static string crashReportErrMsgP2 {
            get {
                return ResourceManager.GetString("crashReportErrMsgP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send failed!.
        /// </summary>
        internal static string crashReportErrorTitle {
            get {
                return ResourceManager.GetString("crashReportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crash report has been sent to the developers.
        ///Sorry for the inconvinience..
        /// </summary>
        internal static string crashReportSentMessage {
            get {
                return ResourceManager.GetString("crashReportSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report sent.
        /// </summary>
        internal static string crashReportSentTitle {
            get {
                return ResourceManager.GetString("crashReportSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clock that rings every hour..
        /// </summary>
        internal static string icoText {
            get {
                return ResourceManager.GetString("icoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and end time cannot be same.
        ///There is no time interval between the given values..
        /// </summary>
        internal static string invalidTimeIntervalMsg {
            get {
                return ResourceManager.GetString("invalidTimeIntervalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Invalid time interval.
        /// </summary>
        internal static string invalidTimeIntervalTitle {
            get {
                return ResourceManager.GetString("invalidTimeIntervalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems there is no connection to the internet. Please connect to the internet..
        /// </summary>
        internal static string noInternetMessage {
            get {
                return ResourceManager.GetString("noInternetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string noInternetTitle {
            get {
                return ResourceManager.GetString("noInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsText {
            get {
                return ResourceManager.GetString("settingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s .
        /// </summary>
        internal static string speakText {
            get {
                return ResourceManager.GetString("speakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off.
        /// </summary>
        internal static string turnoffText {
            get {
                return ResourceManager.GetString("turnoffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Clock alert is available do you want to download the new version?.
        /// </summary>
        internal static string updateAvailable {
            get {
                return ResourceManager.GetString("updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update available.
        /// </summary>
        internal static string updateAvailableTitle {
            get {
                return ResourceManager.GetString("updateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is already the latest version.
        /// </summary>
        internal static string updateNotAvailable {
            get {
                return ResourceManager.GetString("updateNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new update.
        /// </summary>
        internal static string updateNotAvailableTitle {
            get {
                return ResourceManager.GetString("updateNotAvailableTitle", resourceCulture);
            }
        }
    }
}
